dist: trusty
sudo: false

language: node_js
node_js:
  - 8
  - 10

cache:
  yarn: true
  directories:
    - node_modules

install: cd example && yarn && cd ../builders && yarn 

script:
  -  yarn test && yarn build && PACKAGE=`yarn pack`
  - cd ../example && yarn add ../builders/$PACKAGE --dev
